name: HTML5 Validator

on:
  push:
    branches: [ LSW, PYH, LKZ, TKM, LJE ]
  pull_request:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.6.1
        with:
          root: /
          css: true
